#!/bin/bash

set -e

topd=$(pwd)
tstamp=$(date +%Y-%m-%d_%H-%M-%S)
rnd=$RANDOM
wkdir="${topd}/work-${tstamp}-${rnd}"
ddir="${topd}/data"
sdir="${topd}/src"
hdir="/root"

docker run -it -v ${ddir}:${hdir}/data:ro \
       -v ${sdir}:${hdir}/src:ro \
       -v ${wkdir}:${hdir}/work \
       eamon/2015pedv

user=$(id -u)
group=$(id -g)

# Currently, $wdir and its contents are always owned by root, so
sudo chown -hR ${user}:${group} $wkdir 
