#!/bin/bash

set -e

topd=$(pwd)
tstamp=$(date +%Y-%m-%d_%H-%M-%S)
rnd=$RANDOM
wkdir="${topd}/work-${tstamp}-${rnd}"
ddir="${topd}/data"
sdir="${topd}/src"
hdir="/home/docker"

mkdir ${wkdir}
chmod 757 ${wkdir}
docker run -v ${ddir}:${hdir}/data:ro \
       -v ${sdir}:${hdir}/src:ro \
       -v ${wkdir}:${hdir}/work \
       --user docker -w ${hdir} \
       eamon/2015pedv /bin/bash -c "cd ~/work && make -f ../src/Makefile flagSims"
chmod -R 755 ${wkdir}
