#!/bin/bash

set -e

topd=$(pwd)
wkdir="${topd}/work"
ddir="${topd}/data"
sdir="${topd}/src"
hdir="/home/docker"

mkdir ${wkdir} #should error if directory already exists, no overwriting risk
chmod 757 ${wkdir} # in case docker user has different userid, can still write with these perms
docker run -it -v ${ddir}:${hdir}/data:ro \
       -v ${sdir}:${hdir}/src:ro \
       -v ${wkdir}:${hdir}/work \
       --user docker -w ${hdir} \
       --rm=true eamon/2015pedv /bin/bash
chmod -R 755 ${wkdir} # normal file permissions
